/* eslint-disable import/prefer-default-export */
const AVATARS = [
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/242shc_ons_crd_01.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/397uat_ons_crd_01.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/katy_ons_crd_01.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/xialing_ons_crd_01.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/007blp_ons_crd_02.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/wenwu_ons_crd_01.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/012scw_ons_crd_02.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/013vis_ons_crd_01-1.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/cap_ons_crd_01.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/015wsb_ons_crd_03.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/011blw_ons_crd_04.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/017lok_ons_crd_03.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/433ybv_com_crd_01.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/435rgd_com_crd_01.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/173tsk_com_crd_02.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/242shc_com_crd_01.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/037smm_com_crd_01.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/03-knull_com_crd_01.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/007blp_ons_crd_02.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/011blw_ons_crd_04.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/003cap_ons_crd_03.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/111ctt_ons_crd_02.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/140cvg_ons_crd_02.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/009drs_ons_crd_02.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/025drx_ons_crd_02.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/142ebm_ons_crd_02.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/022gam_ons_crd_01-1.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/024grt_ons_crd_01-1.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/116hdl_ons_crd_01-1.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/006hbb_ons_crd_03.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/002irm_ons_crd_03.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/017lok_ons_crd_03.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/045mts_ons_crd_02.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/043neb_ons_crd_03.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/110oky_ons_crd_03.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/141prx_ons_crd_02.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/023rra_ons_crd_03.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/cap_ons_crd_01.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/012scw_ons_crd_02.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/107shr_ons_crd_02.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/005smp_ons_crd_02.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/021slq_ons_crd_02.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/019tha_ons_crd_03.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/004tho_ons_crd_03.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/013vis_ons_crd_01-1.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/042wmr_ons_crd_03.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/015wsb_ons_crd_03.jpg',
	'https://terrigen-cdn-dev.marvel.com/content/prod/1x/079wng_ons_crd_03.jpg',
];

export const getRandomAvatar = () =>
	AVATARS[Math.floor(Math.random() * AVATARS.length)];
