name: Unit Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, latest]
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3
      - name: 'Setup Node.js | Node Version: ${{ matrix.node-version }}'
        continue-on-error: true
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Runs unit tests
        run: npm test
